export const BATH_ACTIONS = {
  SET_BATHS: 'SET_BATHS',
};

export const THERAPY_ACTIONS = {
  SET_THERAPIES: 'SET_THERAPIES',
  SET_THERAPY_OPTIONS: 'SET_THERAPY_OPTIONS',
  SET_CURRENT_THERAPY: 'SET_CURRENT_THERAPY',
};
